apiVersion: v1
kind: Secret
metadata:
  name: gymmanage-secret
  namespace: gymmanage
type: Opaque
stringData:
  SESSION_SECRET: "your_very_secret_session_key"
  MOMO_SECRET_KEY: "test"
  EMAIL_PASS: "test"
