apiVersion: v1
kind: Service
metadata:
  name: gymmanage-service
  namespace: gymmanage
spec:
  selector:
    app: gymmanage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: ClusterIP
