apiVersion: apps/v1
kind: Deployment
metadata:
  name: gymmanage
  namespace: gymmanage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gymmanage
  template:
    metadata:
      labels:
        app: gymmanage
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: gymmanage
          image: docker.io/hung16/gymmanage-app:b5dc6a0
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: gymmanage-config
            - secretRef:
                name: gymmanage-secret
